spring.config.activate.on-profile=prod
spring.datasource.url=jdbc:postgresql://://amazonaws.com
spring.datasource.username=${RDS_USERNAME}
spring.datasource.password=${RDS_PASSWORD}
aws.s3.bucket-name=your-unique-s3-bucket-name
aws.s3.region=your-aws-region
